[package]
name = "nessusparse"
version = "0.1.0"
authors = ["David Young <david.young@nccgroup.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nessus_xml_parser = { "path" = ".." }
clap = "3.0.0-beta.1"